name: log into aws and install nginx

on:
  push:
    branches: main
  pull_request:
    branches: main

env:
  SERVER_IP: ${{ secrets.SERVER_IP }}
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_KEY: ${{ secrets.SSH_KEY }}

jobs:
  deploy-nginx:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
             

      - name: Deploy Nginx on Ubuntu server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            sudo apt update
            sudo apt install -y nginx
            sudo systemctl enable --now nginx
            sudo systemctl status nginx
            sudo systemctl status nginx --no-pager
            sudo cp $GITHUB_WORKSPACE/index.html /var/www/html/index.html

      - name: Deploy index.html to Nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "index.html"
          target: "/var/www/html/"
          script: |
            sudo chown www-data:www-data /var/www/html/index.html
            sudo systemctl restart nginx





          
          

        

  
