name: log into aws and install nginx

on:
  push:
    branches: main
  pull_request:
    branches: main

env:
  SERVER_IP: ${{ secrets.SERVER_IP }}
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_KEY: ${{ secrets.SSH_KEY }}

jobs:
  deploy-nginx:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
             

      - name: Deploy Nginx on Ubuntu server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            sudo apt update
            sudo apt install -y nginx
            sudo systemctl enable --now nginx
            sudo systemctl status nginx
            sudo systemctl status nginx --no-page

      - name: Deploy Nginx index.html
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "index.html"                
          target: "/var/www/html/"           
          script: |
            sudo apt update
            sudo apt install -y nginx
            sudo systemctl enable --now nginx
            sudo chown www-data:www-data /var/www/html/index.html
            sudo chmod 644 /var/www/html/index.html
            sudo systemctl restart nginx

      - name: Verify deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SSH_USER }}
          key: ${{ env.SSH_KEY }}
          port: 22
          script: |
            ls -l /var/www/html/
            cat /var/www/html/index.html





          
          

        

  
